---
- name: Setup Docker environment and deploy application
  hosts: webservers
  become: yes

  vars:
    github_repo_url: "https://github.com/vaibhavkalel1/Quiz-Automation.git"
    docker_image_name: "vaibhavkalel/quiz_app3"
    docker_image_tag: "latest"
    docker_hub_username: "vaibhavkalel"
    docker_hub_password: "vaibhav2115"

  tasks:
    - name: Install system dependencies
      yum:
        name: "{{ item }}"
        state: latest
      loop:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - git
        - python3
        - python3-pip
        - python3-virtualenv
        - python3-setuptools

    - name: Add Docker GPG key
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker
      yum:
        name: docker-ce
        state: latest

    - name: Install docker-py
      pip:
        name: docker-py

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Clone GitHub repository
      git:
        repo: "{{ github_repo_url }}"
        dest: /home/ec2-user/project/Quiz-application

    - name: Build Docker image
      shell: docker build -t {{ docker_image_name }}:{{ docker_image_tag }} /home/ec2-user/project/Quiz-application

    - name: Log in to Docker Hub
      shell: echo "{{ docker_hub_password }}" | docker login --username {{ docker_hub_username }} --password-stdin

    - name: Push Docker image to Docker Hub
      shell: docker push {{ docker_image_name }}:{{ docker_image_tag }}

    - name: Check if container is running
      shell: docker ps -a

    - name: Run Docker container
      shell: docker run -dit --name vaibhavkalel1 -p 8000:8000 {{ docker_image_name }}:{{ docker_image_tag }}

    - name: Show running images
      shell: docker images
