kind: Deployment
apiVersion: apps/v1
metadata:
  name: quiz-app-deployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-app
  template:
    metadata:
      name: quizpod
      labels:
        app: quiz-app
    spec:
      containers:
      - name: quizautomationcontainer
        image: vaibhavkalel/quizautomation:latest
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        ports:
        - containerPort: 8000
