apiVersion: v1
kind: Service
metadata:
  name: quiz-app-service1
spec:
  type: NodePort
  selector:
    app: quiz-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30191 # You can change this to any available port number above 30000